<?php echo $this->getContent(); ?>
<div class="container">
<div class="page_body">
    <table class="content">
        <div class="left_column"><h1>My Hours Log</h1><br>
            <div>
                <div style="float:left; width:400px;">

                    You have: <b>85.98</b><br/>
                    You have/Assigned:
                    <b>48.85%</b><br/>
                    Assigned: <b>176</b><br/>
                    <strong>Ты опоздал:<strong> <b>0 раз</b><br/>

                            <strong>
                                На работе необходимо быть до 9:00. Если опоздали больше 3х раз в месяц, то дисциплина
                                будет считаться не удовлетворительной и негативно скажется на запрос по повышению
                                оклада.
                            </strong>
                            <br>
                            <br>
                            <a style="background: no-repeat;border-bottom: none;" href="https://bit.ly/nightshiftlist"
                               target="_blank"><span class="rainbow-animated">Список Night Shift</span></a>
                            <br>
                            <a href="https://drive.google.com/file/d/1lwIaxf7GFuJI-z1nXYH3Tu9xoK_3ts0U/view?usp=sharing"
                               target="_blank"><span>Праздничный календарь</span></a>
                            <br>

                </div>
                <div style="float: right">
                    <h3>Главные опоздуны</h3>
                    <div>
                        <div style="float: left; padding: 5px 7px; text-align: center">
                        </div>
                        <div style="float: left; padding: 5px 7px; text-align: center">
                        </div>
                        <div style="float: left; padding: 5px 7px; text-align: center">
                        </div>
                    </div>
                </div>
                <div style="float: left; width: 1000px; margin-left: 20px;">
                    <center>
                        <form action="" method="GET">
                            <select name="month" onchange="this.form.submit();" class="form-control">
                                <option value="1">January</option>
                                <option value="2">February</option>
                                <option value="3">March</option>
                                <option value="4">April</option>
                                <option value="5">May</option>
                                <option value="6" selected="selected">June</option>
                                <option value="7">July</option>
                                <option value="8">August</option>
                                <option value="9">September</option>
                                <option value="10">October</option>
                                <option value="11">November</option>
                                <option value="12">December</option>
                            </select>&nbsp;&nbsp;&nbsp;&nbsp;
                            <select name="year" onchange="this.form.submit();" class="form-control">
                                <option value="2009">2009</option>
                                <option value="2010">2010</option>
                                <option value="2011">2011</option>
                                <option value="2012">2012</option>
                                <option value="2013">2013</option>
                                <option value="2014">2014</option>
                                <option value="2015">2015</option>
                                <option value="2016">2016</option>
                                <option value="2017">2017</option>
                                <option value="2018">2018</option>
                                <option value="2019">2019</option>
                                <option value="2020" selected="selected">2020</option>
                            </select>&nbsp;&nbsp;&nbsp;&nbsp;
                        </form>
                    </center>
                    <br>

                    <table class="hours_log" style="float: left;">
                        <thead>
                        <?php foreach ($users as $user) { ?>
                            <td style="padding: 8px 77px; position: relative;
    left: 225px;"><?php echo $user->name ?></td>
                        <?php } ?>
                        </thead>
                        <tbody class="full_day">
                        <td class="day">
                            1<br>
                            <span class="week_day">Monday</span>
                        </td>
                        <?php foreach ($users as $item) { ?>
                            <td style="background-color: #ffb9b2;">
                                <div style="display: inline;" data-type=" test">
                                    <input class="full_day_checkbox_11"
                                           id="day_1" disabled="disabled" value="1" type="checkbox">
                                    <?php foreach ($item->timer as $time) { ?>
                                        <center><?php echo $time->time ?> - <?php echo $time->stop ?></center>
                                    <?php } ?>
                                    <?php $sum = 0;?>
                                    <?php foreach ($item->timer as $time) { ?>
                                       <?php $sum += $time->total_time; ?>
                                    <?php } ?>
                                    <?php if($sum > 0){ ?>
                                    <center><?php echo   round($sum/60,2) ; ?> </center>
                                    <?php } ?>


                                </div>
                            </td>
                        <?php } ?>
                        </tbody>
                    </table>
                    <?php
                    echo $this->tag->form(
                        [
                            "index/timer",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                    ?>
                    <?php echo $time_start?>
                    <?php echo $this->tag->hiddenField(["user_id","type" => "hidden","value"=> $user->id, "class" => "form-control", "id" => "fieldType"]) ?>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button value="start" name="time" type="submit" class="btn btn-success" id="button1" onclick="SwitchButtons('button2');">Start</button>
                            <button value="stop" name="time" type="submit" class="btn btn-success" id="button2" onclick="SwitchButtons('button1');">Stop</button>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                </div>
            </div>

