<?php echo $this->getContent(); ?>

<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table100 ver1 m-b-110">
                <table data-vertable="ver1">
                    <thead>
                    <tr class="row100 head">
                        <th class="column100 column1" data-column="column1"></th>
                        <?php foreach ($users as $user){?>
                        <th class="column100 column2" data-column="column2"><?php echo  $user->name?></th>
                        <?php }?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="row100">
                        <td class="column100 column1" data-column="column1">monday</td>
                        <?php foreach ($users as $item){?>
                            <td class="column100 column2" data-column="column2">
                                <?php foreach ($item->timer as $time){?>
                                    <?php if($time->state === 'start') {?>
                                        <span class="start"><?php echo $time->time ?> -</span>
                                    <?php }else{ ?>
                                        <span class="stop" ><?php echo $time->time ?></span>
                                    <?php }?>
                                <?php }?>
                            </td>
                        <?php }?>
                    </tr>
                    </tbody>
                </table>
            </div>
            <?php
            echo $this->tag->form(
                [
                    "index/timer",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
            ?>
            <?php echo $time_start?>
            <?php echo $this->tag->hiddenField(["user_id","type" => "hidden","value"=> $user->id, "class" => "form-control", "id" => "fieldType"]) ?>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button value="start" name="time" type="submit" class="btn btn-success" id="button1" onclick="SwitchButtons('button2');">Start</button>
                    <button value="stop" name="time" type="submit" class="btn btn-success" id="button2" onclick="SwitchButtons('button1');">Stop</button>
                </div>
            </div>
            <?php echo $this->tag->endForm(); ?>


        </div>
    </div>
</div>
<script>
    function SwitchButtons(buttonId) {
        var hideBtn, showBtn, menuToggle;
        if (buttonId == 'button1') {
            menuToggle = 'menu2';
            showBtn = 'button2';
            hideBtn = 'button1';
        } else {
            menuToggle = 'menu3';
            showBtn = 'button1';
            hideBtn = 'button2';
        }
        //I don't have your menus, so this is commented out.  just uncomment for your usage
        // document.getElementById(menuToggle).toggle(); //step 1: toggle menu
        document.getElementById(hideBtn).style.display = 'none'; //step 2 :additional feature hide button
        document.getElementById(showBtn).style.display = ''; //step 3:additional feature show button


    }

</script>


