<?php echo $this->getContent(); ?>

<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-6 mb-4 mt-4">
            <h1 class="mb-sm-4 pb-sm-2">Change Password</h1>
            <?php
            echo $this->tag->form(
                [
                    "users/changePassword",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
            ?>
                <div class="row form-group">
<!--                    {{ form.label('password', ['class' : 'col-md-3 col-form-lable']) }}-->
                    <div class="col-sm-9">
                        <?php echo $this->tag->textField(["password", "class" => "form-control", "id" => "fieldPassword"]) ?>

                    </div>
                </div>
                <div class="row form-group">
<!--                    {{ form.label('confirmPassword', ['class' : 'col-md-3 col-form-lable']) }}-->
                    <div class="col-sm-9">
                        <?php echo $this->tag->textField(["confirmPassword", "class" => "form-control", "id" => "fieldPassword"]) ?>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-12">
                        <?php echo $this->tag->submitButton(["Change Password", "class" => "btn btn-primary btn-success btn-block"]) ?>
                    </div>
                </div>

            <?php echo $this->tag->endForm(); ?>
        </div>
    </div>
</div>