<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["users", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit users
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "users/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["password", "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMustchangepassword" class="col-sm-2 control-label">MustChangePassword</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["mustChangePassword", "class" => "form-control", "id" => "fieldMustchangepassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProfilesId" class="col-sm-2 control-label">Profiles Of Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["profiles_Id", "type" => "number", "class" => "form-control", "id" => "fieldProfilesId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBanned" class="col-sm-2 control-label">Banned</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["banned", "class" => "form-control", "id" => "fieldBanned"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSuspended" class="col-sm-2 control-label">Suspended</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["suspended", "class" => "form-control", "id" => "fieldSuspended"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActive" class="col-sm-2 control-label">Active</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["active", "class" => "form-control", "id" => "fieldActive"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>

    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<?php
echo $this->tag->form(
    [
        "timer/save",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>
<?php foreach ($timer as $item){?>
    <div class="form-group">
        <label for="fieldActive" class="col-sm-2 control-label">Timer</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["time", "value" => $item->time, "class" => "form-control","onchange" =>"this.form.submit()", "style"=>"width: unset;","id" => "fieldSuspended"]) ?>
            <?php echo $this->tag->textField(["stop", "value" => $item->stop, "class" => "form-control","onchange" =>"this.form.submit()","style"=>"width: unset;", "id" => "fieldSuspended"]) ?>
            <?php echo $this->tag->hiddenField($item->id) ?>
        </div>
    </div>
<?php } ?>

<?php echo $this->tag->endForm(); ?>
