<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
         users
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["users/create", "Create users",'class' => 'btn btn-outline-primary']) ?>

    </p>
</div>

<?php echo $this->getContent() ?>

<?php foreach ($users as $user){?>
    <tr>
        <td>USER : <?php echo $user->name ?></td>
        <?php echo $this->tag->linkTo(["users/edit/".$user->id, "Edit users",'class' => 'btn btn-outline-primary']) ?>
        <hr>
        <br>
    </tr>
<?php }?>
