<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
         users
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["users/create", "Create users",'style'=>'position: relative;left: 8em;bottom: 3em;','class' => 'btn btn-outline-primary']) ?>

    </p>
    <p>
        <?php echo $this->tag->linkTo(["holiday/new", "Create Holiday",'style'=>'position: relative;left: 8em;bottom: 3em;','class' => 'btn btn-outline-primary']) ?>

    </p>
    <p>
        <?php echo $this->tag->linkTo(["late/index", "Late Limit",'style'=>'position: relative;left: 8em;bottom: 3em;','class' => 'btn btn-outline-primary']) ?>

    </p>
</div>

<?php echo $this->getContent() ?>

<?php foreach ($users as $user){?>
    <ul>
        <li>USER : <?php echo $user->name ?></li>
        <li style="color: darkgreen">Email : <?php echo $user->email ?></li>
        <?php if ($user->active == 'N') { ?>
            <li style="color: red">Banned </li>
        <?php } else { ?>
            <li style="color: darkgreen">Active users</li>
        <?php } ?>
        <li style="color: olive">Profile Name : <?php echo $user->profile->name ?></li>
        <?php echo $this->tag->linkTo(["users/edit/".$user->id, "Edit users",'class' => 'btn btn-outline-primary']) ?>
        <hr>
    </ul>
<?php }?>
