<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
         users
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["users/create", "Create users",'class' => 'btn btn-outline-primary']) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php foreach ($users as $user){?>
    <tr>
        <td>USER : <?php echo $user->name ?></td>
        <hr>
        <br>
            <?php foreach ($user->timer as $item){?>
                 <td>time: <?php echo $item->time .' - '. $item->stop ?></td><br>
                <?php
                echo $this->tag->form(
                    [
                        "timer/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal"
                    ]
                );
                ?>

                <div class="form-group">
                    <label for="fieldName" class="col-sm-2 control-label">Start time</label>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(["time", "size" => 30, 'value'=> $item->time,"class" => "form-control", "id" => "fieldName"]) ?>
                        <?php echo $this->tag->hiddenField(["id"=> $item->id]) ?>
                    </div>
                </div>
                <?php echo $this->tag->endForm(); ?>
            <?php }?>
    </tr>
<?php }?>
