
<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "permissions/index",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>
<div class="row d-flex justify-content-center">
    <div class="col-md-8  mb-4 mt-4">
        <h2 class="mb-sm-6 pb-sm-2">Manage permissions</h2>

                   <div class="row mt-4 form-group justify-content-center">
                        <label class="mr-4 col-form-label text-center" for="profileId">Profile</label>
                        <div class="mr-4">
                            <?php echo $this->tag->selectStatic(['profiles_id', $profiles, 'using'=> ['id', 'name'], 'useEmpty' => true, 'emptyText' => '...', 'emptyValue' => '', "class" => "form-control"]) ?>
                        </div>
                        <div class="">
                            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-primary",'name' => 'search']) ?>
                        </div>
                    </div>

        <?php foreach ($profiles as $profile) { ?>
            <?php foreach ($profile->permissions as $permission) { ?>

                <h3><?php echo $permission->resource ?></h3>

                <table class="table table-bordered table-striped" align="center">
                    <thead>
                    <tr>
                        <th width="5%"></th>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>

                    <tr>
                        <td align="center"><input type="checkbox" name="permissions[]"
                                                  value="{{ resource ~ '.' ~ action }}" {% if permissions[resource ~ '.'
                            ~ action] is defined %} checked="checked" {% endif %}>
                        </td>
                        <td>{{ acl.getActionDescription(action) ~ ' ' ~ resource }}</td>
                    </tr>

                    </tbody>
                </table>





            <?php } ?>

        <?php } ?>
        <?php echo $this->tag->submitButton(["Submit", "class" => "btn btn-primary",'name' => 'submit']) ?>

<?php echo $this->tag->endForm(); ?>
