<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["users", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit users
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "timer/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Start Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["time", "size" => 30, "class" => "form-control", "id" => "fieldTime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Stop Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["stop", "size" => 30, "class" => "form-control", "id" => "fieldStop"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Day</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["day", "class" => "form-control", "id" => "fieldDay"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMustchangepassword" class="col-sm-2 control-label">Month</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["month", "class" => "form-control", "id" => "fieldMonth"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProfilesId" class="col-sm-2 control-label">Year</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["year", "type" => "number", "class" => "form-control", "id" => "fieldYear"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBanned" class="col-sm-2 control-label">Total time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["total_time", "class" => "form-control", "id" => "fieldTotalTime"]) ?>
    </div>
</div>



<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>

    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<?php
echo $this->tag->form(
    [
        "timer/save",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>
<?php foreach ($timer as $item){?>
    <div class="form-group">
        <label for="fieldActive" class="col-sm-2 control-label"><?php echo $item->day .'/'.  $item->month .'/'. $item->year?></label>
        <div class="col-sm-10">
            <ul>
                <li><?php echo $item->time?></li>
                <li><?php echo $item->stop?></li>
                <?php echo $this->tag->linkTo(["timer/edit/".$item->id, "Edit users",'class' => 'btn btn-outline-primary']) ?>
            </ul>
        </div>
    </div>
<?php } ?>

<?php echo $this->tag->endForm(); ?>
