<?php echo $this->getContent(); ?>
<div class="container">
    <div class="page_body">
        <table class="content">
            <div class="left_column"><h1>My Hours Log</h1><br>
                <?= $this->tag->linkTo(['session/login', 'Login', 'class'=>'nav-link']) ?>
                <div>
                    <div style="float:left; width:400px;">

                        You have: <b>85.98</b><br/>
                        You have/Assigned:
                        <b>48.85%</b><br/>
                        Assigned: <b>176</b><br/>
                        <strong>Ты опоздал:<strong> <b>0 раз</b><br/>

                                <strong>
                                    На работе необходимо быть до 9:00. Если опоздали больше 3х раз в месяц, то дисциплина
                                    будет считаться не удовлетворительной и негативно скажется на запрос по повышению
                                    оклада.
                                </strong>
                                <br>
                                <br>
                                <a style="background: no-repeat;border-bottom: none;" href="https://bit.ly/nightshiftlist"
                                   target="_blank"><span class="rainbow-animated">Список Night Shift</span></a>
                                <br>
                                <a href="https://drive.google.com/file/d/1lwIaxf7GFuJI-z1nXYH3Tu9xoK_3ts0U/view?usp=sharing"
                                   target="_blank"><span>Праздничный календарь</span></a>
                                <br>

                    </div>
                    <div style="float: right">
                        <h3>Главные опоздуны</h3>
                        <div>
                            <div style="float: left; padding: 5px 7px; text-align: center">
                            </div>
                            <div style="float: left; padding: 5px 7px; text-align: center">
                            </div>
                            <div style="float: left; padding: 5px 7px; text-align: center">
                            </div>
                        </div>
                    </div>
                    <div style="float: left; width: 1000px; margin-left: 20px;">
                        <center>
                            <form action="" method="GET">
                                <select name="month" onchange="this.form.submit();" class="form-control">
                                    <option value="1">January</option>
                                    <option value="2">February</option>
                                    <option value="3">March</option>
                                    <option value="4">April</option>
                                    <option value="5">May</option>
                                    <option value="6" selected="selected">June</option>
                                    <option value="7">July</option>
                                    <option value="8">August</option>
                                    <option value="9">September</option>
                                    <option value="10">October</option>
                                    <option value="11">November</option>
                                    <option value="12">December</option>
                                </select>&nbsp;&nbsp;&nbsp;&nbsp;
                                <select name="year" onchange="this.form.submit();" class="form-control">

                                    <option value="2019">2019</option>
                                    <option value="2020" selected="selected">2020</option>
                                </select>&nbsp;&nbsp;&nbsp;&nbsp;
                            </form>
                        </center>
                        <br>

                        <table class="hours_log" style="float: left;">
                            <thead>
                            <td>Hide/Show</td>
                            <?php foreach ($users as $user) { ?>
                                <td style="padding: 8px 77px; position: relative;left: 150px;"><?php echo $user->name ?></td>
                            <?php } ?>
                            </thead>
                            <tbody class="full_day">
                            <?php $total = 0; ?>
                            <?php for ($d = 1; $d <= 31; $d++) { ?>
                            <tr class="full_day display_none">
                                <td><?php echo $d ?></td>
                                <?php foreach ($users as $item) { ?>

                                        <?php foreach ($item->timer as $time) {?>
                                        <?php if($time->day == $d){?>
                                    <td>
                                        <div style="display: inline;" data-type="test">

                                                <center><?php echo $time->time ?>
                                                    - <?php echo $time->stop ?></center>

                                                <?php
                                                $temp = explode(':', $time->total_time);
                                                $total += intval($temp[2]); // Add the seconds
                                                $total += intval($temp[1]) * 60; // Add the minutes
                                                $total += intval($temp[0]) * 60 * 60; // Add the hours
                                                ?>

                                            <?php if ($total > 0) { ?>
                                                <center><span class="my_total_time"
                                                              style="color: green;"><?php echo gmdate("H:i:s", $total); ?></span>
                                                </center>
                                            <?php } ?>
                                        </div>
                                    </td>
                                        <?php } ?>
                                    <?php } ?>
                                <?php } ?>


                            </tr>
                            <?php } ?>
                            </tbody>

                        </table>

                        <?php
                        echo $this->tag->form(
                            [
                                "timer/timer",
                                "autocomplete" => "off",
                                "class" => "form-horizontal"
                            ]
                        );
                        ?>
                        <?php echo $time_start?>
                        <?php echo $this->tag->hiddenField(["user_id","type" => "hidden","value"=> $user->id, "class" => "form-control", "id" => "fieldType"]) ?>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button value="start" name="time" type="submit" class="btn btn-success" id="button1" onclick="SwitchButtons('button2');">Start</button>
                                <button value="stop" name="time" type="submit" class="btn btn-success" id="button2" onclick="SwitchButtons('button1');">Stop</button>
                            </div>
                        </div>
                        <?php echo $this->tag->endForm(); ?>
                    </div>
                </div>
            </div>
    </div>
</div>

