<?php echo $this->getContent(); ?>
<div class="container">
    <div class="page_body">
        <table class="content">
            <div class="left_column"><h1>My Hours Log</h1><br>

                <div>
                    <div style="float:left; width:400px;">
                        <?php $total = 0; ?>
                        <?php $count = 0; ?>
                        <?php foreach ($users as $item) { ?>
                        <?php foreach ($item->timer as $time){
                        $temp = explode(':', $time->total_time);
                        $total += intval($temp[2]); // Add the seconds
                        $total += intval($temp[1]) * 60; // Add the minutes
                        $total += intval($temp[0]) * 60 * 60; // Add the hours

                        }
                        }
                        ?>
                        You have: <b><?php echo $total_time_in_month->total - gmdate("H:i:s", $total);  ?></b><br/>
                        Assigned: <b><?php echo $total_time_in_month->total ?></b><br/>

                                <strong>
                                    На работе необходимо быть до <?php echo $total_time_in_month->time ?>. Если опоздали больше 3х раз в месяц, то дисциплина
                                    будет считаться не удовлетворительной и негативно скажется на запрос по повышению
                                    оклада.
                                </strong>
                                <br>
                                <br>
                                <a style="background: no-repeat;border-bottom: none;" href="https://bit.ly/nightshiftlist"
                                   target="_blank"><span class="rainbow-animated">Список Night Shift</span></a>
                                <br>
                                <a href="https://drive.google.com/file/d/1lwIaxf7GFuJI-z1nXYH3Tu9xoK_3ts0U/view?usp=sharing"
                                   target="_blank"><span>Праздничный календарь</span></a>
                                <br>

                    </div>
                    <div style="float: right">
                        <h3>Главные опоздуны</h3>
                        <div>
                            <div style="float: left; padding: 5px 7px; text-align: center">
                            </div>
                            <div style="float: left; padding: 5px 7px; text-align: center">
                            </div>
                            <div style="float: left; padding: 5px 7px; text-align: center">
                            </div>
                        </div>
                    </div>
                    <div style="float: left; width: 1000px; margin-left: 20px;">
                        <center>
                            <?php
                            echo $this->tag->form(
                                [
                                    "timer/search",
                                    "autocomplete" => "off",
                                    "class" => "form-horizontal"
                                ]
                            );
                            ?>

                            <div class="form-group" >
                                <label for="fieldActive" class="col-sm-2 control-label">Month</label>
                                <div class="col-sm-10">
                                    <?php echo $this->tag->selectStatic(["month", [1 =>'January',2 =>'February',3 =>'March',4 =>'April',5 =>'May',6 =>'June',7 =>'July',8 =>'August',9 =>'September',10 =>'October',11 =>'November',12 =>'December'], "class" => "form-control","onchange" =>"this.form.submit()", "id" => "fieldActive"]) ?>
                                </div>
                            </div>
                            <div class="form-group" >
                                <label for="fieldActive" class="col-sm-2 control-label">Years</label>
                                <div class="col-sm-10">
                                    <?php echo $this->tag->selectStatic(["year", [1 =>'2021',2 =>'2020'], "class" => "form-control","onchange" =>"this.form.submit()", "id" => "fieldActive"]) ?>
                                </div>
                            </div>
                            <?php echo $this->tag->endForm(); ?>
                        </center>
                        <br>

                        <table class="table" style="float: left;">
                            <thead>
                            <th>hidden/SHow</th>
                            <?php foreach ($users as $user) { ?>
                                <th style="padding: 8px 77px; position: relative;left: 500px;"><?php echo $user->name ?></th>
                            <?php } ?>
                            </thead>
                            <tbody class="full_day">

                            <?php foreach ($period as $dt) { ?>
                                <tr class="full_day display_none">
                                    <?php foreach ($holiday as $value) { ?>
                                        <?php if ($value->day != $dt->format("d")) { ?>
                                            <?php if ($dt->format("l") == 'Sunday' || $dt->format("l") == 'Saturday') { ?>
                                                <td class="table-bordered"
                                                    style="color: green"><?php echo $dt->format(" F d"); ?></td>
                                                <td class="table-bordered"
                                                    style="color: green"><?php echo $dt->format("l"); ?></td>
                                            <?php } else { ?>
                                                <td><?php echo $dt->format("F d"); ?></td>
                                                <td><?php echo $dt->format("l"); ?></td>
                                            <?php } ?>
                                        <?php } ?>
                                        <?php foreach ($users as $item) { ?>
                                            <?php foreach ($item->timer as $time) { ?>
                                                <?php if ($time->day == $dt->format("d") && $time->month == $dt->format("m") && $time->year == $dt->format("Y") && $value->day != $dt->format("d")) { ?>
                                                    <?php if ($time->state == 1) { ?>
                                                        <td style="padding: 8px 77px; position: relative;left: 150px; color: red">
                                                    <?php } else { ?>
                                                        <td style="padding: 8px 77px; position: relative;left: 150px;">
                                                    <?php } ?>
                                                    <div style="display: inline;" data-type="test">

                                                        <center><?php echo $time->time ?>
                                                            - <?php echo $time->stop ?>
                                                        </center>


                                                        <center>
                                                                        <span class="my_total_time"
                                                                              style="color: green;"><?php echo $time->total_time ?></span>
                                                        </center>

                                                    </div>
                                                    </td>
                                                <?php } ?>
                                            <?php } ?>
                                        <?php } ?>
                                    <?php } ?>


                                </tr>
                            <?php } ?>

                            </tbody>

                        </table>

                        <?php
                        echo $this->tag->form(
                            [
                                "timer/timer",
                                "autocomplete" => "off",
                                "class" => "form-horizontal"
                            ]
                        );
                        ?>
                        <?php echo $time_start?>
                        <?php echo $this->tag->hiddenField(["user_id","type" => "hidden","value"=> $user->id, "class" => "form-control", "id" => "fieldType"]) ?>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button value="start" name="time" type="submit" class="btn btn-success" id="button1" onclick="SwitchButtons('button2');">Start</button>
                                <button value="stop" name="time" type="submit" class="btn btn-success" id="button2" onclick="SwitchButtons('button1');">Stop</button>
                            </div>
                        </div>
                        <?php echo $this->tag->endForm(); ?>
                    </div>
                </div>
            </div>
    </div>
</div>


