<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1 style="color: green">
        Limit  late and Limit one month hours
    </h1>
</div>

<?php echo $this->getContent() ?>



<div class="col-md-6">
    <?php foreach ($late as $item) { ?>
        <p>Hours limit : <?php echo $item->time ?></p>
        <p>Month  limit :<?php echo $item->total ?></p>
        <button class="btn btn-light"><?php echo $this->tag->linkTo(["late/edit/".$item->id, "Edit late limit"]) ?></button>
    <?php } ?>
</div>

