<!DOCTYPE html>
<html lang="en">
<head>
    <title>Table V03</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/timer/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/timer/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/timer/css/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/timer/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/timer/perfect-scrollbar/perfect-scrollbar.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/timer/css/util.css">
    <link rel="stylesheet" type="text/css" href="/timer/css/main.css">
    <!--===============================================================================================-->
</head>
<body>
            <?php echo $this->getContent(); ?>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <!--===============================================================================================-->
        <script src="/timer/jquery/jquery-3.2.1.min.js"></script>
        <!--===============================================================================================-->
        <script src="/timer/bootstrap/js/popper.min.js"></script>
        <script src="/timer/bootstrap/js/bootstrap.min.js"></script>
        <!--===============================================================================================-->
        <script src="/timer/select2/select2.min.js"></script>
        <!--===============================================================================================-->
        <script src="/timer/js/main.js"></script>
            <script>

                function hideAccept(){
                    document.getElementById("acceptMe").style.display="none";
                    document.getElementById("rejectMe").style.display="block";
                }

                function hideReject(){
                    document.getElementById("rejectMe").style.display="none";
                    document.getElementById("acceptMe").style.display="block";
                }

            </script>
</body>
</html>
